# Add user
- name: Add user 'node_exporter' with '/sbin/nologin'
  user:
    name: node_exporter
    shell: /sbin/nologin

# Download binary from https://github.com/prometheus/node_exporter/releases/download/v1.0.0-rc.0/node_exporter-1.0.0-rc.0.linux-amd64.tar.gz
- name: Download node_exporter binary from github.com
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /usr/sbin
    remote_src: yes
    extra_opts:
      - "--strip-components"
      - "1"
      - "--no-anchored"
      - "node_exporter"

# Copy startup script
- name: Copy node_exporter startup script in place
  copy:
    src: "{{ role_path }}/files/node_exporter.service"
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'

# Copy config for startup script
- name: Make sure sysconfig directory exist
  file:
    path: /etc/sysconfig
    state: directory
    recurse: yes
    owner: root
    group: root 
    mode: '0755'

- name: Copy node_exporter config script in place
  copy:
    src: "{{ role_path }}/files/node_exporter"
    dest: /etc/sysconfig/node_exporter
    mode: '0644'

# Start service
- name: Reload systemd so new config is read
  systemd:
    daemon_reload: yes

- name: Enable node_exporter service
  systemd:
    name: node_exporter
    enabled: yes
    state: started