server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:8080/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
    pipeline_stages:
    - match:
        selector: '{job="syslog"} |~ "devname=\".*\" devid=\""' # filter for Fortigate log lines
        stages:
        - regex:
          # Try to match following log line
          # ... srcip=192.168.0.67 srcport=57556 srcintf="VLAN-789" srcintfrole="lan" dstip=195.21.71.12 dstport=443 dstintf="dmz" dstintfrole="lan" sessionid=162684798 proto=6 action="accept" policyid=10 ...
          # ... srcip=192.168.0.67 srcport=64810 srcintf="VLAN-789" srcintfrole="lan" dstip=192.168.0.1 dstport=53 dstintf="unknown0" dstintfrole="undefined" sessionid=162882304 proto=17 action="accept" policyid=0
          # ... srcip=192.168.0.226 srcname="CH-SRVFS-0102" srcport=42575 srcintf="VLAN-790" srcintfrole="lan" dstip=192.168.0.1 dstport=53 dstintf="unknown0" dstintfrole="undefined" sessionid=165932933 proto=17 action="accept" policyid=0
            expression: '.* srcip=(?P<srcip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) srcport=(?P<srcport>\d{1,5}) srcintf="(?P<srcintf>[a-zA-Z0-9 _-]*)" .* dstip=(?P<dstip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) dstport=(?P<dstport>\d{1,5}) dstintf="(?P<dstintf>[a-zA-Z0-9 _-]*)" .* proto=(?P<proto>\d{1,2}) action="(?P<action>[a-zA-Z0-9 _-]*)" policyid=(?P<policyid>\d{1,3})'
        - labels:
            srcip:
            srcport:
            srcintf:
            dstip:
            dstport:
            dstintf:
            proto:
            action:
            policyid:

    - match:
        selector: '{job="syslog"} |~ "devname=\".*\" devid=\""' # filter for Fortigate log lines
        stages:
        - regex:
          # Try to match following log line
          # ... srcip=192.168.0.226 srcname="CH-SRVFS-0102" srcport=42575 srcintf="VLAN-790" srcintfrole="lan" dstip=192.168.0.1 dstport=53 dstintf="unknown0" dstintfrole="undefined" sessionid=165932933 proto=17 action="accept" policyid=0
          # ... srcip=192.168.21.02 srcname="CH-CLIW1-2102" srcport=61883 srcintf="VLAN-789" srcintfrole="lan" dstip=172.31.240.5 dstport=53 dstintf="unknown0" dstintfrole="undefined" sessionid=166003946 proto=17 action="accept" policyid=0
          # ... srcip=192.168.0.228 srcname="CH-SRVAD-0101" srcport=44302 srcintf="VLAN-790" srcintfrole="lan" dstip=195.12.70.3 dstport=80 dstintf="VLAN-007" dstintfrole="lan" sessionid=166045049 proto=6 action="close" policyid=38 
            expression: '.* srcip=(?P<srcip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) srcname="[a-zA-Z0-9 _-]*" srcport=(?P<srcport>\d{1,5}) srcintf="(?P<srcintf>[a-zA-Z0-9 _-]*)" .* dstip=(?P<dstip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) dstport=(?P<dstport>\d{1,5}) dstintf="(?P<dstintf>[a-zA-Z0-9 _-]*)" .* proto=(?P<proto>\d{1,2}) action="(?P<action>[a-zA-Z0-9 _-]*)" policyid=(?P<policyid>\d{1,3})'
        - labels:
            srcip:
            srcport:
            srcintf:
            dstip:
            dstport:
            dstintf:
            proto:
            action:
            policyid:

    - match:
        selector: '{job="syslog"} |~ "devname=\".*\" devid=\""' # filter for Fortigate log lines
        stages:
        - regex:
          # Try to match following log line
          # ... srcip=192.168.0.223 dstip=212.13.57.88 srcport=47518 dstport=443 srcintf="VLAN-790" srcintfrole="lan" dstintf="VLAN-007" dstintfrole="lan" proto=6 service="SSL" direction="outgoing" policyid=10
            expression: '.* srcip=(?P<srcip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) dstip=(?P<dstip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) srcport=(?P<srcport>\d{1,5}) dstport=(?P<dstport>\d{1,5}) srcintf="(?P<srcintf>[a-zA-Z0-9 _-]*)" .* dstintf="(?P<dstintf>[a-zA-Z0-9 _-]*)" .* proto=(?P<proto>\d{1,2}) .* policyid=(?P<policyid>\d{1,3}) .* action="(?P<action>[a-zA-Z0-9 _-]*)" '
        - labels:
            srcip:
            srcport:
            srcintf:
            dstip:
            dstport:
            dstintf:
            proto:
            action:
            policyid:

    - match:
        selector: '{job="syslog"} |~ "devname=\".*\" devid=\""' # filter for Fortigate log lines
        stages:
        - regex:
          # Try to match following log line
          # ... srcip=192.168.0.33 identifier=33313 srcintf="VLAN-789" srcintfrole="lan" dstip=46.34.20.21 dstintf="VLAN-007" dstintfrole="lan" sessionid=165531609 proto=1 action="accept" policyid=9
            expression: '.* srcip=(?P<srcip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) identifier=\d* srcintf="(?P<srcintf>[a-zA-Z0-9 _-]*)" .* dstip=(?P<dstip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) dstintf="(?P<dstintf>[a-zA-Z0-9 _-]*)" .* proto=(?P<proto>\d{1,2}) action="(?P<action>[a-zA-Z0-9 _-]*)" policyid=(?P<policyid>\d{1,3})'
        - labels:
            srcip:
            srcintf:
            dstip:
            dstintf:
            proto:
            action:
            policyid:

    - match:
        selector: '{job="syslog"} |~ "devname=\".*\" devid=\""' # filter for Fortigate log lines
        stages:
        - regex:
          # Try to match following log line
          # ... srcip=192.168.0.234 dstip=131.12.50.4 action="login" status="success" reason="none" profile="super_admin" msg="Administrator logged in successfully from https(192.168.0.234)"
            expression: '.* srcip=(?P<srcip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) dstip=(?P<dstip>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}) action="(?P<action>[a-zA-Z0-9 _-]*)" '
        - labels:
            srcip:
            dstip:
            action:
