- name: Make sure config directory exist
  file:
    path: /data/loki/config
    state: directory
    recurse: yes
    owner: root
    group: root 
    mode: '0755'

- name: Make sure data directory exist
  file:
    path: /data/loki/data
    state: directory
    recurse: yes
    owner: root
    group: root 
    mode: '0777'

- name: Copy loki config file to destination
  copy:
    src: "{{ role_path }}/files/loki.yml"
    dest: /data/loki/config/loki.yml
    owner: root
    group: root
    mode: '0644'

- name: Create a dedicated network for prometheus
  docker_network:
    driver: bridge
    name: prometheus_nw

# docker run -v $(pwd):/mnt/config -p 3100:3100 grafana/loki:v1.3.0 -config.file=/mnt/config/loki-config.yaml

- name: Create/Start loki container
  docker_container:
    name: loki
    image: grafana/loki
    state: started
    restart: yes
    restart_policy: always
    detach: yes
    networks:
      - name: prometheus_nw
    ports:
      - "8080:8080"
    command: [
      "-config.file=/etc/loki/loki.yml"
    ]
    volumes:
      - /data/loki/config:/etc/loki:ro
      - /data/loki/data:/mnt
    comparisons:
      image: ignore   # don't restart containers with older versions of the image
      env: strict   # we want precisely this environment
      volumes: allow_more_present   # if there are more volumes, that's ok, as long as `/tmp:/tmp` is there
