- name: Make sure config directory exist
  file:
    path: /data/blackbox-exporter
    state: directory
    recurse: yes
    owner: root
    group: root 
    mode: '0755'

- name: Copy blackbox-exporter config file to destination
  copy:
    src: "{{ role_path }}/files/blackbox.yml"
    dest: /data/blackbox-exporter/blackbox.yml
    owner: root
    group: root
    mode: '0644'

- name: Create a dedicated network for prometheus
  docker_network:
    driver: bridge
    name: prometheus_nw

- name: Create/Start blackbox exporter container
  docker_container:
    name: blackbox-exporter
    image: prom/blackbox-exporter
    state: started
    restart: yes
    restart_policy: always
    detach: yes
    networks:
      - name: prometheus_nw
    ports:
      - "9115:9115"
    command: [
      "--config.file=/mnt/blackbox.yml"
    ]
    volumes:
      - /data/blackbox-exporter/blackbox.yml:/mnt/blackbox.yml:ro
    comparisons:
      image: ignore   # don't restart containers with older versions of the image
      env: strict   # we want precisely this environment
      volumes: allow_more_present   # if there are more volumes, that's ok, as long as `/tmp:/tmp` is there
